# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crypton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for crypton

  target 'cryptonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cryptonUITests' do
    # Pods for testing
  end
pod 'Charts'
end
